name: red_reproduce

channels:
  - conda-forge

dependencies:
    # Base depends
  - python>=3.10
  - red-molsim==0.1.1
  - matplotlib
  - pymbar<4
  - tqdm
  - pandas
  - seaborn
  - ipython
  - ipykernel
  - typer
  - jupyter
  - nbconvert
  - nb-clean
